// Const use in the PORTFOLIO MODULE

export const names = ["Senator Mitch Connell",
    "Senator Kamala Harris",
    "City of Tucson, AZ",
    "The State Bar of California",
    "Cybersecurity and Infrastructure Security Agency",
    "Senator Ben Cardin",
    "Governor of Wyoming",
]

export const text = ["Senator McConnell requires a versatile and responsive website. Themain concern of his office was usability, allowing more direct communication with his constituents. To address this, TRS crafted a solution with the WordPress platform using both cutting-edge and tried-and-true techniques. Some significant UX and design highlights include the mosaic pattern presentation, highlighting new posts, andpress releases for maximum usability. Social media sharing is presentthroughout the website to help disseminate information faster tocitizens in Senator McConnell’s riding. Follow links are accessibleacross the whole site to allow visitors to share content andstrengthen relations with the agency. Finally, the site integrates asmall e-commerce section to allow visitors to purchase flags and otherrelevant products.",
    "For this project, TRS developed a demo website to enhance the presence of Senator Kamala Harris. The base project framework is WordPress CMS with a custom Elementor theme. Further enhancements required additional plugins, including Essential Addons for Elementor, to create a more attractive page. Multimedia files are displayed within a carousel design, creating an interactive area where users can browse new video content. The homepage brings particular attention to upcoming events and the latest news releases, ensuring users get the latest information immediately upon loading the website.",
    "The City of Tucson required an update to its aging website. Paramount amongst their concerns was information delivery. Being a large city, Tucson offers a wide variety of services for its citizens. Immediately, TRS got to work performing a content normalization strategy to inform the UX needs of the future website. With content needs and user experience paths established, TRS design experts crafted a beautiful theme heavily focused on simplicity and usability while highlighting the essence of Tucson. Built with WordPress and using the Elementor page builder plugins, TRS provides the city with a fully-featured and easy-to-edit website for their content and administration staff. Analytics revealed the current website was receiving a fair split of traffic between mobile and desktop users, so special attention was given to the responsive nature of the design. To further enhance usability, the events section links with Google Maps, allowing users to see and find local activity locations easily. Finally, an email subscription form has been synced to popular mail service MailChimp for any user(s) who wish to receive newsletters and keep updated on the latest news and local Tucson events.",
    "The State Bar of California required an institutional site with a sober, straightforward, and understandable presentation. TRS developed a solution created with WordPress CMS and using the Elementor page builder plugin to meet their needs. All pages are entirely adaptable to any media device available. Thumbnail images gallery and recent news section created with a blogging structure to efficiently administer content. The Contact us page includes easy-to-use forms that email the relevant parties on submission and contact details link with Google Maps, so users know where to look when the services are needed.",
    "TRS develop another eye-catching website build with a professional look to represent the most critical Cybersecurity government institution in the USA, The Cybersecurity and Infrastructure Security Agency (CISA). After porting most of the information from the CISA original website, TRS developed a framework to enhance the UI interface and improve the user navigation experience. The entire site was developed with WordPress CMS using the Elementor Page Builder plugin for a core theme. Special add-on plugins include Slider Revolution, allowing content administrators a simple way to create a more attractive and interactive design. The anti-spam software reCAPTCHA3 is present throughout the entire website. ReCAPTCHA3 automatically verifies users’ connection without the need to enter data into text boxes or select images. In addition, contact forms are managed using the Contact Form 7 plugin and linked directly to Google maps to facilitate CISA’s administrative office location(s).",
    "This demo theme is created with WordPress CMS using the Elementor page builder plugins. This configuration allows for the development of complex layouts due to the simple frontend editor. To ensure constituents can always reach the senator, best practices for full responsiveness provide compatibility with all media devices. To help centralize information, TRS establishes seamless integration with the Twitter social media platform via API to display all the live tweets and responses from the Senators feed on the homepage directly. Finally, we link the contact us form to Google Maps and email all relevant parties upon submission.",
    "The Governor of Wyoming office was concerned constituents weren’t able to easily access information on their aging website. TRS stepped up to supply a simple, beautiful, and professional site built with WordPress CMS, alongside the Elementor page builder plugins to improve the appearance. TRS selected the Events Calendar plugin to give users an at-a-glance rundown of local events and appearances by the Governor. Paired with Google maps, citizens can quickly map out exciting events nearby and easily add them to their calendar. Finally, to facilitate constituent outreach, TRS configure API connections so users can subscribe to newsletters and keep updated on the latest news."]